# Generated by Django 5.0.1 on 2024-02-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_info', '0007_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='nom',
        ),
    ]
